# Agenda of Day 1 :     

Numpy
- Vectors
- Matrices
- Numpy arrays
- Sampling from distribution
___

Matplotlib
- Plotting simple curves
- Bar plots, Histogram, Scatter plots
- Contour plots, 3D plots
___
Scipy (If time permits)
- Unconstrained optimization
- Constrained optimization

# Vectors

In [4]:
# import
import numpy as np
import matplotlib as plt

In [5]:
# How to check the version of the libraries
print(f"Numpy version : {np.__version__}")
print(f"Matplotlib version : {plt.__version__}")

Numpy version : 2.0.2
Matplotlib version : 3.10.0


In [7]:
l = [1,2,3]
l

[1, 2, 3]

In [8]:
# consider it as a vector
a = np.array([1,2,3])
a

array([1, 2, 3])

## Python Lists

In [11]:
a = [1,2,3]
b = [4,5,6]


s = a+b # <--- it will concatenate the lists
s

[1, 2, 3, 4, 5, 6]

In [14]:
# To add the elements in a list we have to use for loop
# `zip` function do element wise tuples

x = [1,2,3]
y = [4,5,6]
z = []

for x_i , y_i in zip(x,y) :
  z.append(x_i + y_i)

z

[5, 7, 9]

## Vector as NumPy arrays

In [15]:
x = np.array([1,2,3])
x

array([1, 2, 3])

## Vector Addition


In [24]:
# Why not python lists use ?

x = [1,2,3]
y = [4,5,6]
z = x + y
z

[1, 2, 3, 4, 5, 6]

In [25]:
# In Numpy :

x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
z

array([5, 7, 9])

## Element-wise multiplication

In [28]:
# Why not python lists use ?

x = [1,2,3]
y = [4,5,6]
# z = x * y  # <--- throws an eror
# z

In [20]:
# [1*4, 2*5, 3*6]
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y
z

array([ 4, 10, 18])

## Scaling vectors

In [34]:
# Why not python lists use ?

x = [1,2,3]
y = 3 * x
y

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [32]:
# In Numpy :
x = np.array([1,2,3])
y = 0.5 * x
y

array([0.5, 1. , 1.5])

## Element-wise funtions of vectors

`Example 1` :  f(x) = x^2


In [37]:
x = np.array([1,2,3,4])
y = x**2
y

array([ 1,  4,  9, 16])

`Example 2.1` : f(x) = log10(x) where base is 10

In [39]:
x = np.array([1, 10, 100, 1000, 10_000, 100_000])
np.log10(x)

array([0., 1., 2., 3., 4., 5.])

`Example 2.2` : f(x) = log(x) where base is e

In [45]:
x = np.array([1, 10, 100, 1000, 10_000, 100_000])
np.log(x)

array([ 0.        ,  2.30258509,  4.60517019,  6.90775528,  9.21034037,
       11.51292546])

In [46]:
x = np.array([1, np.e, np.e**2, np.e**3])
np.log(x)

array([0., 1., 2., 3.])

`Example 3` : f(x) = x + c

In [48]:
x = np.array([1,2,3])
x + 5

array([6, 7, 8])

`Example 4` : f(x) = 5x - 2

In [49]:
x = np.array([1,2,3])
5*x - 2

array([ 3,  8, 13])

## Dot Product

In [52]:
# 1*(-4) + 2*(-5) + 3*(-6) + 4 * (-7)
# -4 - 10 -18 - 28 = -60

x = np.array([1,2,3,4])
y = np.array([-4,-5,-6,-7])
np.dot(x,y)

np.int64(-60)

In [53]:
x @ y

np.int64(-60)

## Vector of zeros or ones

In [55]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [60]:
zeros = np.zeros(3)
zeros + 3

array([3., 3., 3.])

In [56]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [59]:
x = np.ones(5)
x + np.array([1,2,4,6,8])

array([2., 3., 5., 7., 9.])

In [62]:
# All the elements are equal to 5
fives = np.ones(5) * 5
fives

array([5., 5., 5., 5., 5.])

## Range

In [79]:
a = list(range(5))
a

[0, 1, 2, 3, 4]

In [81]:
a = np.array(range(5))
a

array([0, 1, 2, 3, 4])

In [83]:
a = list(range(0,5,2))
a

[0, 2, 4]

In [84]:
# arange = array + range
np.arange(1,6,2)

array([1, 3, 5])

## Norm of a vector

L2 norm is defined as :      

||x||2 = sqrt(1**2 + 2**2 + 2**2) = sqrt(14)

In [90]:
np.sqrt(14)

np.float64(3.7416573867739413)

In [88]:
x = np.array([1,2,3])
L2 = np.linalg.norm(x)
L2

np.float64(3.7416573867739413)

`NOTE` : By default, the norm computed is the L2 norm. If we want to compute L1 norm, we have to pass an additional argument to the funtion.

L1 norm is defined as :     

||x||1 = |1| + |2| + |3| = 1 + 2 + 3 = 6

In [94]:
x = np.array([-1,-2,-3])
L1 = np.linalg.norm(x, ord = 1)
L1

np.float64(6.0)

## Shape & Dimension of a vector

In [95]:
# Shape
x = np.array([1,2,3,4])
x.shape

(4,)

In [96]:
# N - dim
x = np.array([1,2,3,4])
x.ndim

1