# Matrices

In [2]:
import numpy as np

## Matrix as a NumPy array

In [4]:
M = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Shape of a matrix
M.shape

(3, 3)

In [6]:
# dimension of a matrix [ [], [], [] ]
M.ndim

2

## Adding two matrices

In [9]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

A + B

array([[ 6,  8],
       [10, 12]])

## Scaling a Matrix

In [11]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
M * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

## Element-wise multiplication of matrices

In [14]:
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
C = A * B
C

array([[ 5, 12],
       [21, 32]])

## Element-wise functions of matrices

`Example 1` :  f(x) = |x|

In [18]:
A = np.array([[-1, 2], [-3, -4]])

np.abs(A)

array([[1, 2],
       [3, 4]])

`Example 2` : B = A^2

In [20]:
A = np.array([
    [1,np.sqrt(2)],
    [np.sqrt(3), 2]
])

A**2

array([[1., 2.],
       [3., 4.]])

`Example 3` : Transpose of a matrix

In [47]:
M = np.array([
    [1,2,3],
    [4,5,6]
])

print("Original matrix :", M)
print("The dimension of M is :", M.shape)

M_T = np.transpose(M)

print("Transpose is :",M_T )
print("The dimension of transpose is :", M_T.shape)

Original matrix : [[1 2 3]
 [4 5 6]]
The dimension of M is : (2, 3)
Transpose is : [[1 4]
 [2 5]
 [3 6]]
The dimension of transpose is : (3, 2)


In [23]:
# Alternatively

M = np.array([
    [1,2,3],
    [4,5,6]
])

M.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

## Vectors as matrices

In [51]:
X = np.array([
    [1],
    [2],
    [3]
])
print(X.shape)
print(X.ndim)
X

(3, 1)
2


array([[1],
       [2],
       [3]])

In [54]:
X = np.array([
    [1,2,3]
])
print(X.shape)
print(X.ndim)
X

(1, 3)
2


array([[1, 2, 3]])

## Products of two matrices

In [58]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [6,7],
    [8,9],
    [10,11]
])

# C = A @ B  # <--- (Dot product)
C = np.dot(A,B)
C

array([[ 52,  58],
       [124, 139]])

### Product of a matrix and a (column) vector

In [61]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
X = np.array([6,7,8])

C = A @ X
C

array([ 44, 107, 170])

### Product of (row) vector and a matrix

In [65]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
X = np.array([6,7,8])

C = X @ A
C

array([ 90, 111, 132])

## (Inner) Product of a (row) vector and a (column) vector

In [67]:
# Inner product = transpose(x) . y

X = np.array([1,2,3])
y = np.array([4,5,6])

# X @ y
np.dot(X,y)

np.int64(32)

## (Outer) Product of a (column) vector and a (row) vector

In [71]:
# Outer Product = X . transpose(y)

X = np.array([1,2,3])
y = np.array([4,5,6])

np.outer(X,y)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

## Matrix of zeros

In [73]:
M = np.zeros((2,4))
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matrix of ones

In [75]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Identity Matrix

In [81]:
M = np.eye(5)
M

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Diagonal Matrices

In [83]:
M = np.diag([1,2,3,4])
M

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Indexing & Slicing

`Example 1` :  Indexing

In [85]:
M = np.array([
    [1,3,0],
    [4,2,5],
    [9,8,2]
])

M[1][2]

np.int64(5)

In [86]:
# Alternatively

M = np.array([
    [1,3,0],
    [4,7,5],
    [9,8,2]
])
M[1,2]

np.int64(5)

`Example 2` : Row-slice

In [92]:
M = np.array([1,2,3,4,5,6])
M.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
M = np.array([1,2,3,4,5,6])
M.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
M = np.array([1,2,3,4,5,6])
N = M.reshape(6,1)
O = N.flatten()  # <--- convert it into a vector
O

array([1, 2, 3, 4, 5, 6])

`Example 3` : Column Slice

In [105]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
M[ : , 1]

array([2, 5, 8])

`Example 4` : Submatrix slice

In [109]:
M = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

M[ 1:3, 2:4]

array([[ 7,  8],
       [11, 12]])

## Other Matrix Operation

In [113]:
M = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

np.linalg.matrix_rank(M)

np.int64(2)

## Inverse of a matrix

In [116]:
M = np.array([
    [3,-4],
    [4,3]
])

np.linalg.inv(M)

array([[ 0.12,  0.16],
       [-0.16,  0.12]])

## Pseudoinverse

In [118]:
M = np.array([[1,2,3], [3,6,9]])
np.linalg.pinv(M)

array([[0.00714286, 0.02142857],
       [0.01428571, 0.04285714],
       [0.02142857, 0.06428571]])

## Eigenvalues & Eigenvectors

In [127]:
M = np.array([[1,0,-3], [0,5,2], [-3, 2, 8]])

eigval = np.linalg.eigvals(M)
eigval

# eigval, eigvec = np.linalg.eigh(M)
# eigval

array([ 9.84353554, -0.20942046,  4.36588492])